# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c5944984e3f5a66e3b1b590fb05b3005263b3989866988c59c3b2e31b3ac2b73eb1cbc2408ae13e85cf3da9d6aaf5dbf81f923dd6b5b32cabb302a24d8cb0ef

test:
  secret_key_base: 596215dd9e7d5817105a003d3c4ba4a86dcf73979aea8582d3db21751db279db11bcc40048fe80bf18cf1ade6bf2406f4812a8dbef9efaa1a85645d306679d95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
